spring:
  config:
    activate:
      on-profile: "dev"
  datasource:
    url: "jdbc:h2:mem:subscriptiondb"
    driverClassName: "org.h2.Driver"
    username: "sa"
    password: ""
    jpa:
      show-sql: true
      database-platform: "org.hibernate.dialect.H2Dialect"
      defer-datasource-initialization: true
      generate-ddl: true
      hibernate:
        ddl-auto: update
    # Enabling H2 Console
  h2:
    console:
      enabled: true
      path: "/h2"